type = "webpack"

name = "deka-collection"
account_id = "21f21d9f5c226ec6b0325b46209bc0d9"

workers_dev = true

[env.production]
workers_dev = false
zone_id = "10c8e82d4b989bf095668d43da5068ec"
route = "https://deka.narusejun.com/*"

[site]
bucket = "../ui/build"
entry-point = "./"
